[tool.black]
include = '\.pyi?$'
skip-string-normalization = true
requires = [
    'python-jose[cryptography]>=3.2.0',
    'python-secrets>=3.9.2',
]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
